# first name is the planner name "RRTStar_planner"
RRTStar_planner:
  goal_tolerence : 0.5
  radius : 2.0
  epsilon : 0.2
  max_num_nodes : 5000
  min_num_nodes : 2
  search_specific_area : true
  map_width : 20.0
  map_height : 20.0